### ISSUE TITLE
How to store weights as 2-bit values and scaling factors

### ISSUE THREAD

**Issue by pgadosey** [TropComplique/trained-ternary-quantization#2]
Hi, 
   After testing I have my saved model size in MB unchanged. How do you store your trained model as 2-bit values and scaling factors?

Thanks

**Comment by TropComplique** [comment]
Simple example how to save quantized values as `int8`:

```python
import numpy as np

# full precision weights
x = np.random.randn(5000, 5000).astype('float32')
np.save('x.npy', x)  # 96 MB

# quantization
threshold = 0.7
x[x > threshold] = 1.0
x[np.logical_and(x <= threshold, x >= -threshold)] = 0.0
x[x < -threshold] = -1.0
x = x.astype('int8')
np.save('quantized_x.npy', x)  # 24 MB
```

In case of CNN weights, you have to find an appropriate 
data structure to store 2-bit values.
Maybe try `numpy.packbits`.

**Comment by pgadosey** [comment]
Got it.Thanks for the snippet.
